### ISSUE TITLE
SpatialCapture scene unable to load Map

### ISSUE THREAD

**Issue by qudy2001** [Placenote/PlacenoteSDK-Unity#45]
Hi,

I have put the API keys and map ID, when tried to click "Add planes and PointCloud"

I got this

Extracting planes from xxxxxxxx-5e4b-4642-ac48-xxxxxxxxx
UnityEngine.Debug:Log(Object)

**NullReferenceException: Object reference not set to an instance of an object
EditorCoroutines.PlacenoteWebAPI+<AddMeshCoroutine>c__Iterator1.MoveNext () (at Assets/Placenote/Toolkits/SpatialCapture/PlacenoteWebAPI.cs:115)
EditorCoroutines.EditorCoroutines.MoveNext (EditorCoroutines.EditorCoroutine coroutine) (at Assets/Placenote/EditorCoroutines/Scripts/EditorCoroutines.cs:337)
EditorCoroutines.EditorCoroutines.OnUpdate () (at Assets/Placenote/EditorCoroutines/Scripts/EditorCoroutines.cs:320)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:191)**

**Comment by pmukherj** [comment]
Hello, 

It seems you haven’t used the Placenote Spatial Capture app to create this map? I’ll send you a private message with details on getting the Capture app which will fix this issue.

**Comment by qudy2001** [comment]
Ah, that's right! I used the random shape scene to create this map. I try to download it with placenote/capture, the installrapp always shows sync fail, I installed the profile and trusted it, dont know what is going on there. Thanks!

**Comment by pmukherj** [comment]
Got a link to the right app. 
https://placenote.com/docs/unity/tutorials/spatial-capture/
