### ISSUE TITLE
Bypassing FireBase

### ISSUE THREAD

**Issue by smtabatabaie** [Placenote/PlacenoteSDK-Unity#46]
Hi, I'm trying to use placenote and on some ISPs it only works via VPN , I suspect it is because Firebase as some ISPs has banned it. I wanted to ask if there are any ways to bypass FireBase and not using it or a way to use a proxy inside placenote.
Thanks

**Comment by y22ma** [comment]
Hi @smtabatabaie, unfortunately we don't have a way to bypass our backend currently. It is required enable key product experience in the SDK such as map synchronization.
