### ISSUE TITLE
I follow the steps to build, I found a mistake，SDK not initialized

### ISSUE THREAD

**Issue by zhijie-gao** [Placenote/PlacenoteSDK-Unity#5]
libPlacenote, PNSetFrame Vertical Mapping SDK not initialized, please call PNInitialize

**Comment by pmukherj** [comment]
hey @zhijie-gao, 
Thanks for pinging us on this! Can you check two things?
a) Do you have an API key entered under the PlacenoteCameraManager component? 
b) Are you connected to the internet?

**Comment by zhijie-gao** [comment]
I have entered the correct key and the network is normal

**Comment by pmukherj** [comment]
Hey @zhijie-gao, 

Sorry for the trouble. Do you mind joining us on Slack so we can privately, confirm user information (email etc.). 
You can get on slack by using this [link ](https://join.slack.com/t/placenotedevs/shared_invite/enQtMjk5ODk2MzM0NDMzLTIzMjQwZTAxMzYxYWMyMjY1NzZmYTA2YjY0OGU5NzAzNjUxN2M1ZTQ1ZWZiYzI4ZDg4NGU1ZjQ0ZTA4NDY0OWI)

**Comment by zhijie-gao** [comment]
ok

**Comment by y22ma** [comment]
@zhijie-gao just wondering if you are still experiencing this issue?

**Comment by y22ma** [comment]
Closing this issue as the author is not available to provide more update.
