### ISSUE TITLE
Extending a captured map in the Spatial Capture sample

### ISSUE THREAD

**Issue by masterchief1s1k** [Placenote/PlacenoteSDK-Unity#52]
Hi,
I have successfully following the steps in the Unity Spatial Capture documentation found [here](https://placenote.com/docs/unity/tutorials/spatial-capture/). Now i would like to extend the sample app to try building a larger scale map. However i noticed that the Capture app on Testflight crash when the scanning map is getting too big (for me it was about 10x10m room and any further the app would crash). 
So there are 2 things that i hope i can get some assistance with:
1. Is there some available method to extend an existing map? I did try extending the map following the doc [here](https://placenote.com/docs/unity/tutorials/extending-a-map/) but the obtained map is of different format as far as i can understand (No plane obtained)
2. I wonder how would the app store and download the map as the map size can get big real fast, and is there a way to store the obtained map locally on the app?

**Comment by pmukherj** [comment]
Hello @masterchief1s1k !
Please direct questions about the spatial capture app on our slack for a faster response (https://placenote.com/slack). We'll look through our reported stack traces for your crash! The spatial capture app should be comfortable with spaces more than 10mx10m rooms. 

Closing this for code-related questions about the Unity Sample App! Do come find us on slack so we can get your user/timing info related to the Spatial capture app.
