### ISSUE TITLE
Placenote Not initialized

### ISSUE THREAD

**Issue by ShreenathManikandaswamy** [Placenote/PlacenoteSDK-Unity#54]
<img width="581" alt="Screenshot 2019-06-28 at 2 29 53 PM" src="https://user-images.githubusercontent.com/20485909/60331616-aac86900-99b2-11e9-9935-b89c7301bd71.png">
Hi,

I have multiple scene setup with placenote. Do i have to stop session and start session everytime i start a new scene? Because in the editor i am getting the output perfectly but when i build it is not working. One of the developers in Slack suggested me to "LibPlacenote.instance.Init()" Which says "PNInitialize already initialized" But when i Debug with "LibPLacenote.instance.initialize()" I get "Placenote Not initialized" Can you tell me what mistake i am doing..

Any support will be greatly appreciated.

Thanks.

**Comment by pmukherj** [comment]
This is a known issue right now and here’s how you can solve it. Basically you need to call the “Init()” function every time you switch a scene.

Go to LibPLacenote.cs and search for the Init() function
https://github.com/Placenote/PlacenoteSDK-Unity/blob/8a01592831b4888c251d3f91753042cce8a83a2f/Assets/Placenote/LibPlacenote/LibPlacenote.cs#L660

You need to make this “public” from private.
You’ll notice that we are calling Init in the Awake function for LibPLacenote. I think that the reason it doesn’t initialize when you switch a scene is that this function may not be getting called in the new scene. So in your start function - call LibPlacenote.Instance.Init()

We'll have a fix for this in subsequent releases!
