### ISSUE TITLE
No Device Camera with Lightweight Render Pipeline

### ISSUE THREAD

**Issue by nanoTitan** [Placenote/PlacenoteSDK-Unity#55]
I'm on Unity 2019.1.11f1, and it appears that the device camera never works. I do get a prompt to allow the camera, but it shows nothing but a blue background with any of the samples. The iOS version is 12.4. Projects built with the normal 3D version are working, just not using LRP.

**Comment by pmukherj** [comment]
Hello!
Please route all troubleshooting questions to the support forums as per: https://docs.placenote.com/support
LRP is not supported yet! We'll be working on that soon. 

Thank you.
