### ISSUE TITLE
On Windows PostBuildTrigger.cs copies whole folder into build

### ISSUE THREAD

**Issue by ephb** [Placenote/PlacenoteSDK-Unity#58]
When building your SDK on Windows the PostBuildTrigger script does not produce the desired result.
The whole folder of the framework gets copied into the build folder which then causes the framework signing check of the app to fail when installing the ipa to device.

**Comment by pmukherj** [comment]
Sorry, Window's builds are not supported for iOS devices as per Apple requirements. Our build process is focussed towards building on MacOSX devices. Some folks have been able to build pretty easily on Virtual Machines if you want to give that a try. 

More details here: https://docs.placenote.com/supported-devices

**Comment by ephb** [comment]
That is not true, Unity on Windows supports iOS as target platform.
You can build the Unity Project on Windows and then build the Xcode project on a Mac or with Unity Cloud Build.

The device requirements page you linked lists Unity as requirement and not specifically Unity for Mac. 

This script is the only thing preventing this from working as changing it or removing the files manually from the build allows the project to be built and deployed successfully.

**Comment by pmukherj** [comment]
We've clarified the requirement for a Mac on our supported devices pages, thanks for finding that! Unity for Windows for iOS builds has a host of issues post build (esp with ARFoundation). We'll add support for Unity for Windows when we come to Windows with Android in the near future.

**Comment by ephb** [comment]
There are no problems apart from this. I am building ARFoundation projects on Windows quite often and I have also used your SDK before.  Deleting the offending .meta files manually remedies the problem. 
I will investigate further and then make a pull request.

**Comment by pmukherj** [comment]
Okay! If you want to submit a PR, I'll re-open this ticket. I can test things on this side as well.

**Comment by ephb** [comment]
We created a fork that allows building on Windows. I did not make a pull-request since we did not test on macOS yet. But I will leave this link here in case anyone runs into the same problem.
https://github.com/vrtx-labs/PlacenoteSDK-Unity
