### ISSUE TITLE
error Thread 1: Signal SIGABRT

### ISSUE THREAD

**Issue by MohanRam1996** [Placenote/PlacenoteSDK-Unity#60]
the placenote frame work is not found error. the weird thing i have added it propely following the videos. but still its throughing an error. the app as successly build but while running its crashing and throwing the above error. i have even added description for camera and location as well. can any one guide me.

**Comment by pmukherj** [comment]
Hello!
Please route all troubleshooting questions to the support forums as per: https://docs.placenote.com/support
