### ISSUE TITLE
When build app with Xcode after Unity, "Placenote.framework/Placenote' does not contain bitcode"

### ISSUE THREAD

**Issue by Kyle0936** [Placenote/PlacenoteSDK-Unity#62]
I did see this as a common problem on the troubleshooting page but the issue still existed even after I have disabled Bitcode for the project. I have followed the steps here: https://docs.placenote.com/unity/build-the-sample-apps/run-on-an-ios-device

![image](https://user-images.githubusercontent.com/32176299/117684940-0e935e00-b1e8-11eb-9ea4-35580ecedfeb.png)

Many thanks in advance!

**Comment by pmukherj** [comment]
Hello!
Please route all troubleshooting questions to the support forums as per: https://docs.placenote.com/support

In this particular situation you may just have to reset the build (Clean Build) and delete the binary! XCode seems to not be applying that setting properly.
